### ISSUE TITLE
Interface doesn't load correctly

### ISSUE THREAD

**Issue by srulikbd** [bigscience-workshop/promptsource#416]
I'm running on windows 10 with python 3.9
the web interface used to worked until I tried cloning the repo again..
this is the error:

```streamlit run promptsource/pr
omptsource.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.0.0.101:8501

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 116, i
n spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 125, i
n _main
    prepare(preparation_data)
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 236, i
n prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 287, i
n _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 97, in _run_module_cod
e
    _run_code(code, mod_globals, init_globals,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Desktop\Srulik\Work\HuggingFace\BigScience\promptsource\promptsource\promptsource
.py", line 34, in <module>
    state = _get_state()
  File "C:\Users\User\Desktop\Srulik\Work\HuggingFace\BigScience\promptsource\promptsource\session.py",
 line 84, in _get_state
    session = _get_session()
  File "C:\Users\User\Desktop\Srulik\Work\HuggingFace\BigScience\promptsource\promptsource\session.py",
 line 74, in _get_session
    session_id = get_report_ctx().session_id
AttributeError: 'NoneType' object has no attribute 'session_id'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 116, i
n spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 125, i
n _main
    prepare(preparation_data)
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 236, i
n prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\user\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 287, i
n _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 97, in _run_module_cod
e
    _run_code(code, mod_globals, init_globals,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Desktop\Srulik\Work\HuggingFace\BigScience\promptsource\promptsource\promptsource
.py", line 34, in <module>
    state = _get_state()
  File "C:\Users\User\Desktop\Srulik\Work\HuggingFace\BigScience\promptsource\promptsource\session.py",
 line 84, in _get_state
    session = _get_session()
  File "C:\Users\User\Desktop\Srulik\Work\HuggingFace\BigScience\promptsource\promptsource\session.py",
 line 74, in _get_session
    session_id = get_report_ctx().session_id
AttributeError: 'NoneType' object has no attribute 'session_id'
```

**Comment by stephenbach** [comment]
I'm not sure of the root cause, but can you try downgrading to Python 3.8? I've seen that fix this error on OSes other than Windows.

**Comment by srulikbd** [comment]
I have got the same problem using python 3.8
what else should I do?

thx!

**Comment by srulikbd** [comment]
I restored the previous code which was ok, and now it's also working so I'm fine with it.

**Comment by tianjianjiang** [comment]
Just FYI: I've encontered a different issue with session on macOS but not as serious as yours. Therefore I guess something isn't stable with session states.

On the other hand, if you have time to try it, I would recommend you switch to WSL if haven't. (Judging by the error message you provided.)

**Comment by wade3han** [comment]
Hello, @srulikbd @tianjianjiang. I encountered same issue on macOS, and I can't find the way to solve this.
My environment has `streamlit==0.82.0`, and I worked on `fa7a84d`. My python version is 3.8.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/wade/miniconda3/envs/promptsource/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/wade/miniconda3/envs/promptsource/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/wade/miniconda3/envs/promptsource/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/wade/miniconda3/envs/promptsource/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/wade/miniconda3/envs/promptsource/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/wade/miniconda3/envs/promptsource/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/wade/miniconda3/envs/promptsource/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/wade/promptsource/promptsource/promptsource.py", line 34, in <module>
    state = _get_state()
  File "/Users/wade/promptsource/promptsource/session.py", line 84, in _get_state
    session = _get_session()
  File "/Users/wade/promptsource/promptsource/session.py", line 74, in _get_session
    session_id = get_report_ctx().session_id
AttributeError: 'NoneType' object has no attribute 'session_id'
```

**Comment by tianjianjiang** [comment]
@wade3han Please try #411 and let me know whether it works or not, thank you!

**Comment by wade3han** [comment]
Thank you, but it is not working again unfortunately. With the same error.

**Comment by tianjianjiang** [comment]
@wade3han
> Thank you, but it is not working again unfortunately. With the same error.

I just tested and confirmed that only python37 will work.

A brief background:
Mac had 2 significant changes that python must address accordingly. One is the Apple Silicon (M1), another is the strict policy of unsafe `fork()`. Therefore, python38 (backported from python39) is the minimum requirement for M1, and its multiprocessing by default uses `spawn()` instead of `fork()`.

Please open a new issue ticket for the `spawn()` error you encountered, and then I will try to figure out how to make a compatible streamlit-based implementation for both python37 and python38.

In the meantime, please try to use python37.
For macOS, I recommend either `pyenv` or `sudo port select python` of MacPorts.

**Comment by wade3han** [comment]
@tianjianjiang Oh it works! Thanks. Downgrading the version of python (3.8 -> 3.7) works.
