### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'session_id'

### ISSUE THREAD

**Issue by manandey** [bigscience-workshop/promptsource#588]
Hi,

Is anyone facing this issue while running `streamlit run promptsource/app.py` ?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\I355109\Anaconda3\envs\python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\I355109\Anaconda3\envs\python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\I355109\Anaconda3\envs\python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\I355109\Anaconda3\envs\python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\I355109\Anaconda3\envs\python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\I355109\Anaconda3\envs\python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\I355109\Anaconda3\envs\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\I355109\promptsource\promptsource\app.py", line 59, in <module>
    state = _get_state()
  File "c:\users\i355109\promptsource\promptsource\session.py", line 84, in _get_state
    session = _get_session()
  File "c:\users\i355109\promptsource\promptsource\session.py", line 74, in _get_session
    session_id = get_report_ctx().session_id
AttributeError: 'NoneType' object has no attribute 'session_id'
```

**Comment by srulikbd** [comment]
yeah I run again into the same issue.
windows 11, python 3.7 
I tried the updated promptsource package..

**Comment by srulikbd** [comment]
I tried installing it on ubuntu 20.04 (WSL) but encountered the problem of : "streamlit: command not found"

**Comment by MagedSaeed** [comment]
@srulikbd 

> I tried installing it on ubuntu 20.04 (WSL) but encountered the problem of : "streamlit: command not found"

Maybe a basic comment, but that means `streamlit` is not installed on your environment. Are you sure you run `pip install -r requirements.txt` on your virtualenv and activated itit?

**Comment by srulikbd** [comment]
yeah I installed it this way..
I tried again (without installing anything again) and surprisingly, now it's working smoothly on ubuntu 20.04 (WSL).

**Comment by srulikbd** [comment]
for future reference, anyone using WSL ubuntu 20.04, you should install python 3.7, because it ships with python 3.8..
use the following:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7
sudo apt install python3-pip
alias pip='python3.7 -m pip'
```
and if streamlit isn't recognized, a WSL restart might help.

**Comment by ProjectMountiainMan** [comment]
I am having this same issue on windows 10. Is the accepted fix meant to be installing in WSL?

**Comment by tianjianjiang** [comment]
> I am having this same issue on windows 10. Is the accepted fix meant to be installing in WSL?

Probably just like what @srulikbd said above?
https://github.com/bigscience-workshop/promptsource/issues/588#issuecomment-955745086
