### ISSUE TITLE
'metadata' is undefined for P3 data

### ISSUE THREAD

**Issue by harrylyf** [bigscience-workshop/promptsource#824]
Hi, I am trying to use the `bigscience/p3` dataset to fine-tune my model. Specifically `adversarial_qa_dbert_answer_the_following_q`. However, I am experiencing `jinja2.exceptions.UndefinedError: 'metadata' is undefined` Error.
I used the code from Readme but modified it a bit for my specific dataset.

Code executed:
```
from promptsource.templates import DatasetTemplates
test = DatasetTemplates('adversarial_qa','dbert')
prompt = test["answer_the_following_q"]
from datasets import load_dataset
dataset = load_dataset("bigscience/P3", "adversarial_qa_dbert_answer_the_following_q", split="train")
example = dataset[1]
result = prompt.apply(example)
```
Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fruitbasket/users/*/miniconda3/envs/tfew/lib/python3.7/site-packages/promptsource/templates.py", line 188, in apply
    rendered_example = rtemplate.render(**protected_example)
  File "/fruitbasket/users/*/miniconda3/envs/tfew/lib/python3.7/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/fruitbasket/users/*/miniconda3/envs/tfew/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/fruitbasket/users/*/miniconda3/envs/tfew/lib/python3.7/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'metadata' is undefined
```

Can anyone help with this? Thanks!!

**Comment by sbmaruf** [comment]
P3 dataset (`"bigscience/P3", "adversarial_qa_dbert_answer_the_following_q"`) is already prompted dataset. The json metadata is in the following format, 
```
{
    "source": 
    "target": 
    "prompt_name":
    "split_name": 
}
```

The template that you are trying to run can only be applied to the original dataset. The following code works.
```
from promptsource.templates import DatasetTemplates
test = DatasetTemplates('adversarial_qa','dbert')
prompt = test["answer_the_following_q"]
from datasets import load_dataset
dataset = load_dataset('adversarial_qa','dbert')['train']
example = dataset[1]
result = prompt.apply(example)
print(result)
```

**Comment by harrylyf** [comment]
Got it, it worked. Thank you so much!
